apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgserver-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  browser.auth: {{ .Files.Get "files/secrets/browser.auth" | b64enc }}
  controller.auth: {{ .Files.Get "files/secrets/controller.auth" | b64enc }}
  supass: {{ .Files.Get "files/secrets/supass" | b64enc }}
  secrets.py: {{ .Files.Get "files/secrets/django/secrets.py" | b64enc }}