name: OS setup

runs:
  using: 'composite'
  steps:
    - name: Free space (Ubuntu only)
      if: runner.os == 'Linux'
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        swap-storage: false
        large-packages: false
        
        android: true
        dotnet: true
        haskell: true
        docker-images: true
    - name: Install OpenCL, EGL and uv (Ubuntu only)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ocl-icd-opencl-dev libegl1 libgles2 mesa-utils libxcb-cursor0 libxcb-xinerama0 libxcb-util1 libxcb-keysyms1 libxcb-randr0 libxkbcommon-x11-0 libegl1-mesa-dev
        wget -qO- https://astral.sh/uv/install.sh | sh
    - name: Install coreutils and uv (macOS only)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install coreutils uv
    - name: Install uv (Windows only)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
