name: Categorize projects

inputs:
  subprojects:
    required: true
outputs:
  notebook:
    value: ${{ steps.group-subprojects.outputs.notebook }}
  python:
    value: ${{ steps.group-subprojects.outputs.python }}
  gradio:
    value: ${{ steps.group-subprojects.outputs.gradio }}
  webcam:
    value: ${{ steps.group-subprojects.outputs.webcam }}
  qt:
    value: ${{ steps.group-subprojects.outputs.qt }}
  js:
    value: ${{ steps.group-subprojects.outputs.js }}
  unittest:
    value: ${{ steps.group-subprojects.outputs.unittest }}

runs:
  using: 'composite'
  steps:
    - name: Group subprojects
      id: group-subprojects
      shell: bash
      run: |
        notebook=()
        python=()
        gradio=()
        webcam=()
        qt=()
        js=()

        for dir in ${{ inputs.subprojects }}; do
          if [ -f "$dir/package.json" ]; then
            js+=("$dir")
          elif find "$dir" -maxdepth 1 -name "*.ipynb" | grep -q "."; then
            notebook+=("$dir")
          elif [ -f "$dir/requirements.txt" ] && grep -q "gradio" "$dir/requirements.txt"; then
            gradio+=("$dir")
          elif [ -f "$dir/requirements.txt" ] && grep -iq "pyside" "$dir/requirements.txt"; then
            qt+=("$dir")
          elif [ -f "$dir/main.py" ] && grep -q -- "--stream" "$dir/main.py"; then
            webcam+=("$dir")
          elif [ -d "$dir/test" ]; then
            unittest+=("$dir/test")
          else
            python+=("$dir")
          fi
        done

        notebook_json=$(printf '%s\n' "${notebook[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        python_json=$(printf '%s\n' "${python[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        gradio_json=$(printf '%s\n' "${gradio[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        webcam_json=$(printf '%s\n' "${webcam[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        qt_json=$(printf '%s\n' "${qt[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        js_json=$(printf '%s\n' "${js[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        unittest_json=$(printf '%s\n' "${unittest_json[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')

        echo "notebook=$notebook_json" >> $GITHUB_OUTPUT
        echo "python=$python_json" >> $GITHUB_OUTPUT
        echo "gradio=$gradio_json" >> $GITHUB_OUTPUT
        echo "webcam=$webcam_json" >> $GITHUB_OUTPUT
        echo "qt=$qt_json" >> $GITHUB_OUTPUT
        echo "js=$js_json" >> $GITHUB_OUTPUT
        echo "unittest_json=$unittest_json" >> $GITHUB_OUTPUT
    - name: Print subprojects to test
      shell: bash
      run: |
        echo "Notebook subprojects: ${{ steps.group-subprojects.outputs.notebook }}"
        echo "Python subprojects: ${{ steps.group-subprojects.outputs.python }}"
        echo "Gradio subprojects: ${{ steps.group-subprojects.outputs.gradio }}"
        echo "Webcam subprojects: ${{ steps.group-subprojects.outputs.webcam }}"
        echo "Qt subprojects: ${{ steps.group-subprojects.outputs.qt }}"
        echo "JS subprojects: ${{ steps.group-subprojects.outputs.js }}"
        echo "Unit test subprojects: ${{ steps.group-subprojects.outputs.unittest }}"
