name: Hugging Face model pre downloading

on:
  workflow_call:

jobs:
  download-models:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        shell: bash
        run: |
          wget -qO- https://astral.sh/uv/install.sh | sh && mv "$HOME/.local/bin/uv" /usr/local/bin/uv
      - uses: ../reusable-steps/setup-hugging-face
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-model-${{ github.event.pull_request.number || github.run_id }}
      - name: Pre-download some HF models
        shell: bash
        run: |
          python -c "from huggingface_hub import snapshot_download; snapshot_download('meta-llama/Llama-3.2-3B-Instruct', resume_download=True)"
      - name: Upload models as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hf-models
          path: ~/.cache/huggingface
