permissions:
  contents: read
name: Hugging Face model pre downloading

on:
  workflow_call:
    secrets:
      HF_TOKEN:
        required: true
        description: Hugging Face token

jobs:
  download-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/reusable-steps/setup-os
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: ./.github/reusable-steps/setup-hugging-face
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
      - name: Cache Hugging Face models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-model-${{ github.event.pull_request.number || github.run_id }}
      - name: Pre-download some HF models
        shell: bash
        run: |
          python -c "from huggingface_hub import snapshot_download; snapshot_download('meta-llama/Llama-3.2-3B-Instruct', resume_download=True)"
