# This workflow will install Python dependencies and run tests with multiple versions of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sanity check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  find-subprojects:
    runs-on: ubuntu-latest
    outputs:
      subprojects: ${{ steps.get-subprojects.outputs.subproject_list }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get list of Python subprojects (with requirements.txt)
        id: get-subprojects
        run: |
          # Find all directories in 'demos' that contain a requirements.txt file, excluding 'utils'
          subprojects=$(find . -type f -name "requirements.txt" -exec dirname {} \; | sort -u)
          subproject_list=$(echo "$subprojects" | jq -R -s -c 'split("\n")[:-1]')
          echo "$subproject_list"
          echo "subproject_list=$subproject_list" >> $GITHUB_OUTPUT  # Use GITHUB_OUTPUT file for setting outputs
                    
  check-repo:
    needs: find-subprojects
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.9, 3.13]
        subproject: ${{ fromJson(needs.find-subprojects.outputs.subprojects) }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies for ${{ matrix.subproject }}
      run: |
        python -m pip install --upgrade pip
        pip install -r ./demos/${{ matrix.subproject }}/requirements.txt
