name: Reusable Sanity Python Job

on:
  workflow_call:
    inputs:
      subprojects:
        description: "List of subprojects"
        required: true
        type: string

      python_versions:
        description: "Python versions"
        required: false
        type: string
        default: '["3.10"]'

jobs:
  run-python:
    name: Run Python Subprojects
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025]
        python: ${{ fromJson(inputs.python_versions) }}
        subproject: ${{ fromJson(inputs.subprojects) }}

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup OS dependencies
      - name: Setup OS
        uses: ./.github/reusable-steps/setup-os

      # 3. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      # 4. Setup project dependencies
      - name: Install dependencies
        uses: ./.github/reusable-steps/setup-python
        with:
          python: ${{ matrix.python }}
          project: ${{ matrix.subproject }}

      # 5. Run project
      - name: Run project
        shell: bash
        run: |
          cd ${{ matrix.subproject }}
          python main.py