name: OS setup

runs:
  using: 'composite'
  steps:
    - name: Install coreutils
      if: runner.os == 'macOS'
      run: |
        brew install coreutils
    - name: Install virtual display
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
