name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"


permissions: read-all  # Required by https://github.com/ossf/scorecard/blob/e23b8ad91fd6a64a0a971ca4fc0a4d1650725615/docs/checks.md#token-permissions


jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked because it has been open for 30 days with no activity. It is scheduled to close in 14 days."
          close-issue-message: "This issue was closed automatically because it has been inactive for 14 days since being marked as stale. Please reopen if needed."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
